### ISSUE TITLE
Use GitHub Actions build as status checks

### ISSUE THREAD

**Issue by kdambekalns** [neos/team#50]
Now that we have a new build to replace Travis (see https://github.com/neos/flow-development-collection/pull/2273 and https://github.com/neos/flow-development-collection/pull/2390 and some more commits until now), we need to use them as required status checks:

<img width="949" alt="Screenshot 2021-02-24 at 09 06 44" src="https://user-images.githubusercontent.com/95873/108967723-2430c700-7680-11eb-8dd9-651239285693.png">

To make that easy and future-proof, we need to create an utility job as per https://github.community/t/status-check-for-a-matrix-jobs/127354/7 – then we can enable that one job as required check.

- [x] Flow dev collection
- [x] Neos dev collection

**Comment by albe** [comment]
https://github.com/actions/toolkit/issues/581 might become an issue, especially in combination with "experimental" = `continue-on-error` builds. See also https://github.com/actions/runner/issues/2347 - "continue-on-error" does not behave like travis' "allow-failure"

**Comment by albe** [comment]
Hm, that buildall job seems to fail if the build was skipped (due to `[skip *]` commit message): https://github.com/neos/flow-development-collection/runs/1969158010?check_suite_focus=true

Probably the `if: ${{ always() }}` is not quite right in our case? I'd expect that to match the `if:` of the `build` job: 
`if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[skip travis]')"`

**Comment by kdambekalns** [comment]
> "continue-on-error" does not behave like travis' "allow-failure"

Right, but when the job continues after a step is failing, the job still passes, no?

**Comment by kdambekalns** [comment]
> that buildall job seems to fail if the build was skipped

Gah! Probably right…

**Comment by kdambekalns** [comment]
Skipping hopefully skips now…

**Comment by albe** [comment]
Works great now. Once https://github.com/neos/neos-development-collection/pull/3291 is in, we can enable it for Neos

**Comment by albe** [comment]
Set the required checks for the neos collection, so this can be closed :)
